# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/
services:
  frontend:
    build:
      context: ./frontend
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    command: mongod
    ports:
      - 127.0.0.1:27017:27017